# Generated by Django 5.2.5 on 2025-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
