# Generated by Django 5.2.5 on 2025-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_submission_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attendee_type',
            field=models.CharField(choices=[('vips', 'VIPS Student'), ('outsider', 'Outsider')], default='outsider', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='vips_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='vips_ids/'),
        ),
    ]
