# Generated by Django 5.2.5 on 2025-08-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_submission_attendee_type_submission_vips_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='vips_id_card',
            field=models.ImageField(default='', upload_to='vips_ids/'),
            preserve_default=False,
        ),
    ]
