# Generated by Django 5.2.5 on 2025-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_submission_vips_id_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'permissions': [('can_edit_kiosk_submission', 'Can edit kiosk submission details')]},
        ),
        migrations.AlterField(
            model_name='submission',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='vips_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='vips_ids/'),
        ),
    ]
