# Generated by Django 5.2.5 on 2025-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_submission_options_alter_submission_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pass_type',
            field=models.CharField(choices=[('day1', 'Day 1 Pass'), ('combo', 'Combo Pass')], default='day1', max_length=10),
        ),
    ]
