# Generated by Django 5.2.5 on 2025-08-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_submission_pass_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'permissions': [('can_edit_kiosk_submission', 'Can edit kiosk submission details'), ('can_change_status_fields', 'Can change email sent and checked in status')]},
        ),
    ]
