# Generated by Django 5.2.5 on 2025-08-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_kioskrequest_processed_at_kioskrequest_processed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskrequest',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='kioskrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='kioskrequest',
            name='status',
        ),
    ]
